### ISSUE TITLE
NameError: name 'method' is not defined

### ISSUE THREAD

**Issue by kura** [dropbox/pyannotate#29]
When using pyannonate to generate and apply annotations, one of the the return values I have is a method. Pyannotate generates the following return value:

```python
# ... -> method
```

When using this return value, I get the following error:

```python
NameError: name 'method' is not defined
```

I'm not sure exactly what this return type should be changed to. I can't point it at a specific method using single quotes, i.e.

```python
# ... -> 'some_method'
```

Because it can return one of a number of methods.

So what would the correct value actually be?

**Comment by JukkaL** [comment]
The best we can easily do is to generate `Callable` (or `Callable[..., Any]`) as the type instead of `method`. We already do that transformation for some other types, so the implementation will be trivial (just add a line around https://github.com/dropbox/pyannotate/blob/master/pyannotate_tools/annotations/parse.py#L49).

**Comment by kura** [comment]
@JukkaL thanks. So just like https://github.com/dropbox/pyannotate/issues/19 basically.
